# Generated by Django 4.0.1 on 2022-04-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
