# Generated by Django 4.0.1 on 2022-04-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pizza',
            new_name='product',
        ),
    ]
